---
name: escaped
version: 1.0.0.0
synopsis: Produce Text with terminal escape sequences
description: See README.md
category: Text
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
copyright: 2018 Patrick Brisbin
license: MIT
github: pbrisbin/escaped

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.7 && < 5

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - quickcheck-instances
    - text
    - unix

executables:
  escaped-example:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - escaped
      - text

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - escaped
      - hspec
      - quickcheck-properties

  doctest:
    main: Main.hs
    source-dirs: doctest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
