name: escaped
version: 1.1.0.0
synopsis: Produce Text with terminal escape sequences
description: See README.md
category: Text
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
copyright: 2018 Patrick Brisbin
license: MIT
github: pbrisbin/escaped

extra-doc-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: "impl(ghc >= 9.8)"
    ghc-options:
      - -Wno-missing-role-annotations
      - -Wno-missing-poly-kind-signatures
  - condition: "impl(ghc >= 9.2)"
    ghc-options:
      - -Wno-missing-kind-signatures

dependencies:
  - base >= 4 && < 5

default-extensions:
  - DerivingStrategies
  - ImportQualifiedPost
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - quickcheck-instances
    - text
    - unix

executables:
  escaped-example:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - escaped
      - text

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - escaped
      - hspec
      - quickcheck-properties

  doctest:
    main: Main.hs
    source-dirs: doctest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
