name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: find -maxdepth 1 -name 'stack*.yaml' -printf '"%f"\n' | sort -V | jq --slurp
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  test:
    needs: generate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - id: stack
        uses: freckle/stack-action@v5
        with:
          stack-arguments: --coverage
          compiler-tools: hpc-lcov
        env:
          STACK_YAML: ${{ matrix.stack-yaml }}

      - if: ${{ matrix.stack-yaml == 'stack.yaml' }}
        run: |
          tix='${{ steps.stack.outputs.local-hpc-root }}/combined/all/all.tix'
          stack exec -- hpc-lcov --file "$tix"

      - if: ${{ matrix.stack-yaml == 'stack.yaml' }}
        uses: codecov/codecov-action@v4
        with:
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: warning
